### ISSUE TITLE
Permettre à l'utilisateur de voir l'historique de ses points

### ISSUE THREAD

**Issue by lioneltuttle** [lioneltuttle/gamification-server#12]
Permettre à l'utilisateur de voir l'historique de ses points
Grace à l'audit

**Comment by lioneltuttle** [comment]
On se connecte comme utilisateur
Rajouter un menu historique, utiliser un ion-icon:
<ion-icon name="file-tray-full-outline"></ion-icon>

![image](https://user-images.githubusercontent.com/20986777/79077380-7d5e6900-7d01-11ea-8871-8bbed6ca6edd.png)


Ensuite utiliser le AuditPointsService eT leAudit BadgesService et créer une page comme celle la:

![image](https://user-images.githubusercontent.com/20986777/79077534-c82cb080-7d02-11ea-90ae-fbb59d65ad0c.png)

La page commence par la date la plus récente.

Rajouter une ligne chaque fois que des points sont transformés en badges ou quand des badges sont transformés en d'autres badges.

Rajouter une ligne quand des points sont remis à zéro.

**Comment by jinghong91** [comment]
Il n'y a ni AuditBadgesService ni table DB audit_badge.
Si je comprend bien, on fait "select jhi_date from  points_audit where user_id=:id;" puis pour chaque date "select * from point where user_id=:id and jhi_date=:date;" ?

Est-il besoin de filtrer d'autres colonnes dans point_audit?

**Comment by lioneltuttle** [comment]
Oui pour la 1ere requete.

En fait, il ne faut afficher que les nouveaux points.

Je ne me souvenais plus, mais effectivement, tu as tout dans PointsAudit normalement

**Comment by lioneltuttle** [comment]
Pas besoin de la seconde requete

**Comment by jinghong91** [comment]
Mais il n'y a pas info de point dans le table Point.
![image](https://user-images.githubusercontent.com/16400648/81067820-9660d100-8edf-11ea-83ea-6b9da35c5a0b.png)

**Comment by lioneltuttle** [comment]
Il faudrait les rajouter.
Comme ca la table porterait mieux son nom :)

**Comment by jinghong91** [comment]
Les donnes dans la table points_audit sont les changements des badge, comment on peut ajouter la valeur de point total?

**Comment by lioneltuttle** [comment]
On n'affiche pas la valeur totale mais juste les points rajoutés
